INSERT INTO clientes(apellido_paterno, apellido_materno, identidad, nombres, contrasena, correo, genero,fecha_nacimiento,fecha_creacion) VALUES('Catañeda','Rios','73672312','Carla Sofia','123456','carla@gmail.com','Femenino','2004-045-04',NOW());
INSERT INTO clientes(apellido_paterno, apellido_materno, identidad, nombres, contrasena, correo, genero,fecha_nacimiento,fecha_creacion) VALUES('Dominguez','Ramos','73642312','Ronald Andre','543210','andre@gmail.com','Masculino','2000-02-02',NOW());
INSERT INTO clientes(apellido_paterno, apellido_materno, identidad, nombres, contrasena, correo, genero,fecha_nacimiento,fecha_creacion) VALUES('Quintana','Quispe','73672123','Carla Sofia','3232323','carla@gmail.com','Femenino','1999-06-03',NOW());
INSERT INTO clientes(apellido_paterno, apellido_materno, identidad, nombres, contrasena, correo, genero,fecha_nacimiento,fecha_creacion) VALUES('Sosa','Paredes','73672132','Ana Claudia','23233','ana@gmail.com','Femenino','2002-07-04',NOW());
INSERT INTO clientes(apellido_paterno, apellido_materno, identidad, nombres, contrasena, correo, genero,fecha_nacimiento,fecha_creacion) VALUES('Gambeta','Solorzano','73672322','Juan Isac','7473922','juan@gmail.com','Masculino','2001-08-04',NOW());
INSERT INTO clientes(apellido_paterno, apellido_materno, identidad, nombres, contrasena, correo, genero,fecha_nacimiento,fecha_creacion) VALUES('Romani','Contreras','73672111','Julio Cesar','123julioce','julio@gmail.com','Masculino','2005-02-05',NOW());

INSERT INTO admins(apellido_materno, apellido_paterno, identidad,codigo, contrasena, correo, genero, nombres) VALUES('Laurente','Espinoza','73035832','123','123','lucas@usmp.pe','Masculino','Lucas');
INSERT INTO admins(apellido_materno, apellido_paterno, identidad,codigo, contrasena, correo, genero, nombres) VALUES('Quinteros','Palomino','73035833','1234','123','Leonardo@usmp.pe','Masculino','Aitor');
INSERT INTO admins(apellido_materno, apellido_paterno, identidad,codigo, contrasena, correo, genero, nombres) VALUES('Valencia','Hernandez','73035834','1235','123','katherine@usmp.pe','Femenino','Katherine');
INSERT INTO admins(apellido_materno, apellido_paterno, identidad,codigo, contrasena, correo, genero, nombres) VALUES('Villarreal','Carrasco','73035835','1236','123','rodrigo@usmp.pe','Masculino','Rodrigo');

INSERT INTO platos(nombre_plato,descripcion,precio,imagen) VALUES('PACHAMANCA A LA OLLA','A base de carne de res, de cerdo, cordero o pollo; sazonado con las especias de chincho, culantro y ají; acompañado con papas, camote, yuca, choclo y habas.','45','/images/imagesCatalogo/imgPachamanca.jpg');
INSERT INTO platos(nombre_plato,descripcion,precio,imagen) VALUES('CUY CHACTADO','Cuy frito en abundante aceite hecho bajo una piedra, acompañado con papas hervidas, camote, habas y sarza de cebolla.','40','/images/imagesCatalogo/cuyChactado.jpg');
INSERT INTO platos(nombre_plato,descripcion,precio,imagen) VALUES('OCOPA','Salsa a base de huacatay y ají mirasol servido sobre papas hervidas; acompañado de lechuga, huevo cocido y aceitunas negras','20','/images/imagesCatalogo/ocopa.jpg');
INSERT INTO platos(nombre_plato,descripcion,precio,imagen) VALUES('ROCOTO RELLENO','Relleno de carne, almendras y pasas, cubierto por una capa de queso fundido; acompañado de lechuga, trozos de tomate y una porción de pastel de papa','35','/images/imagesCatalogo/rocotoR.jpg');
INSERT INTO platos(nombre_plato,descripcion,precio,imagen) VALUES('CALDO DE MOTE','Caldo a base de maíz mote y carne de carnero; acompañado de perejil y cebolla china','30','/images/imagesCatalogo/CaldoMote.jpg');
INSERT INTO platos(nombre_plato,descripcion,precio,imagen) VALUES('CHUPE DE HABAS','Caldo a base de habas, papas picadas, huevo, queso; acompañado de perejil y culantro picado','25','/images/imagesCatalogo/chupHabas.jpg');